apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: backendconfig
  namespace: {{ .Values.namespace }}
spec:
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 1800
