apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hostname-app.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{ "default": "backendconfig" }'
    cloud.google.com/neg: '{ "ingress": true }'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 9376
  selector:
    {{- include "hostname-app.selectorLabels" . | nindent 4 }}
